/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./components/bottomNav/bottomNav.vue')['default']
    HeaderBar: typeof import('./components/headerBar/headerBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./components/buttons/themeToggler/themeToggler.vue')['default']
  }
}
